### ISSUE TITLE
Setting width & height of the player

### ISSUE THREAD

**Issue by CodeCurosity** [vlitejs/vlite#109]
### Describe the bug

I set the width and height in options but it doesn't seem to accept?

### Steps to reproduce

Set width & height in options

### Expected behavior

to change width and height of player

### Vlite.js

5.0.2

### Browser

114

### OS

mac os 13.4

**Comment by yoriiis** [comment]
Hello @CodeCurosity, there is no option in the constructor to set the width and height. It is set in CSS with the aspect-ratio property.

**Comment by CodeCurosity** [comment]
can you give an example? also how do we make this function work player.pause(); i tried everything and there is no way of pausing or playing the video outside onReady function?

**Comment by yoriiis** [comment]
I strongly recommend you to manipulate the player only when it is ready, so inside the `onReady` function.

The following listener on a button will toggle the play.

```js
new Vlitejs('#player', {
  onReady: function (player) {
    document.querySelector('#btn').addEventListener('click', (e) => {
      // if (player.elements.outerContainer.classList.contains('v-paused')) {
      if (player.isPaused === null || player.isPaused) {
        player.play()
        e.currentTarget.innerText = 'Pause'
      } else {
        player.pause()
        e.currentTarget.innerText = 'Play'
      }
    })
  }
})
```

```html
<button id="btn">Play</button>
```

You have two ways to detect the state of the player, with the `player.isPaused` property or with the CSS class `v-paused` on the parent element. The `player.isPaused` is set to `null` before the first start and will be a boolean after.

**Comment by CodeCurosity** [comment]
Can you help me on how can i make the player play and pause in the slider change as it always say its not a function even though player in console log showing fine.

```
	var mySwiper = new Swiper('.swiper-container', {
		effect: 'flip',
		spaceBetween: 10,
		slidesPerView: 1,
		simulateTouch: true,
		navigation: {
		  nextEl: '.swiper-button-next',
		  prevEl: '.swiper-button-prev',
		},
		on: {
		  slideChange: function () {
			players.forEach((player, index) => {
			  if (index === mySwiper.previousIndex) {
				player.pause(); // Pause the player
	  
			  } else if (index === mySwiper.activeIndex) {
				player().play(); // Play the player
			  }
			});
		  },
		},
	  });
```
