### ISSUE TITLE
Make area to click seeking bar wider

### ISSUE THREAD

**Issue by ignl** [vlitejs/vlite#117]
### If the feature request is for a plugin or provider, specify it here.

control-bar

### If the feature solves a problem you have, specify it here.

It's relatively hard to move video back and forth with vlitejs control bar. It seems the line that you have to hit is very thin and you must be very precise I often miss it and pause the video accidentally. If you try youtube player you can notice it's basically impossible to pause video accidentally because it's much more forgiving if you are few pixels over the line it will still seek instead of pausing the video.

### Describe the proposed feature.

Make control-bar seeking line click area wider.

**Comment by yoriiis** [comment]
Thanks @ignl for the report. It's true that it was a little too thin.
Can you look at the changes and test on your side too (#119)?

**Comment by ignl** [comment]
Much better, thanks!
