### ISSUE TITLE
Control bar height issue on Firefox

### ISSUE THREAD

**Issue by mgibbs189** [vlitejs/vlite#126]
### Describe the bug

Height looks correct in Chrome; way too tall in Firefox.

Seems related to this recent commit: https://github.com/vlitejs/vlite/commit/6fc9c350b88ece7e819575eb8689c41efeedf91e

Not sure why the extra  `+ 10px` in the CSS?

### Steps to reproduce

Compare the controlbars between Chrome and Firefox. Screenshots below.

### Expected behavior

Consistent controlbar heights across browsers

### Screenshots and recordings

Chrome 122:
<img width="168" alt="Screenshot 2024-03-18 at 2 25 24 PM" src="https://github.com/vlitejs/vlite/assets/115410/ac2555d6-711b-4c4d-915e-43a3fd798055">
Firefox 123.0.1:
<img width="210" alt="Screenshot 2024-03-18 at 2 25 37 PM" src="https://github.com/vlitejs/vlite/assets/115410/feb4cb22-2fc3-4101-ab13-81387c525633">

### Vlite.js

6.0.2

### Browser

Chrome 122, Firefox 123.0.1

### OS

macOS 14.4

### Additional context

Thanks for your great work on this project, btw :)

**Comment by yoriiis** [comment]
Hello @mgibbs189, thanks for your feedback, appreciate!

The fix will soon be available in the next release.
