### ISSUE TITLE
YouTube video playback doesn't start when the video is muted

### ISSUE THREAD

**Issue by carelevers** [vlitejs/vlite#132]
### Describe the bug

When attempting to start playback of a YouTube video while it is muted, the video doesn't start. This issue occurs in chrome or chromium based browsers. It behaves normally in firefox.

### Steps to reproduce

The issue also occurs in the provided glitch demo playground : https://glitch.com/edit/#!/vlitejs-youtube-video

However, i noticed this playground runs on vlite-js release 5, so I remixed a glitch environment to vlite-js 6.0.3 where the issue also occurs: https://glitch.com/edit/#!/sage-quilted-hippopotamus

It also works when you preview in a new window with glitch, but it doesn't work when it's previewed in the preview pane

### Expected behavior

Youtube video's should playback whether muted or unmuted.

### Screenshots and recordings

https://github.com/vlitejs/vlite/assets/11197996/0854bc89-a8ee-4752-9348-471a66c41b1a

### Vlite.js

6.0.3

### Browser

Chrome 126.0.6478.62 (Officiële build) (64-bits)

### OS

Windows 11

**Comment by carelevers** [comment]
Hello @yoriiis, thanks for the quick response, 

I updated the issue with a screen recording of this example: https://glitch.com/edit/#!/sage-quilted-hippopotamus, in a Chrome incognito window with all extensions disabled.

**Comment by yoriiis** [comment]
@carelevers I think the issue is on Glitch only. Do you reproduce the same issue outside of this site?

**Comment by carelevers** [comment]
Hmm, yes, I am also experiencing the same issue on some sites where we use vlite with the YouTube provider. Additionally, in other sandbox environments, the issue persists: https://jsfiddle.net/a3tv6zpf/
[

https://github.com/vlitejs/vlite/assets/11197996/cec70615-84dc-42d7-a284-4fed131525ce

](url)


I don't know if there are other ways to reproduce this behavior?

**Comment by carelevers** [comment]
I also receive a warning when autoplay is set to true and muted is set to true. When I unmute the video, I get the following warning:
![afbeelding](https://github.com/vlitejs/vlite/assets/11197996/d9e2929b-aef2-444c-b8fc-8f2f2d9ee312)

**Comment by yoriiis** [comment]
Sorry for the delay, I think the problem is visible when the player is inside an other iframe. Glitch and JSFiddle use iframe to sandbox the content.

The url of the Glitch iframe works: https://vlitejs-youtube-video.glitch.me
But if I create an iframe with this url, the problem is visible.

Are you using Vlitejs in an iframe? Normally the problem is only present in this case.

**Comment by yoriiis** [comment]
> I also receive a warning when autoplay is set to true and muted is set to true. When I unmute the video, I get the following warning: ![afbeelding](https://private-user-images.githubusercontent.com/11197996/343800162-d9e2929b-aef2-444c-b8fc-8f2f2d9ee312.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMDM0OTEsIm5iZiI6MTcyMjAwMzE5MSwicGF0aCI6Ii8xMTE5Nzk5Ni8zNDM4MDAxNjItZDllMjkyOWItYWVmMi00NDRjLWI4ZmMtOGYyZjJkOWVlMzEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDE0MTMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3NDBjZjk3MWFjNTQ0MzE5ZDM1NGQ0ZDc1ZjRmNGMzMGIzYWNhMWFhOGQ3NDhiYzkzZjdhZjRhYmMxMGQ3MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZJ4eJfiV7rGfbAEZovXe8LjE_UZLJmf9TmfRY1F-fEs)

This warning is normal because automatic playback with sound requires user interaction; it is the browser that decides whether sound will be activated, not Vlitejs.

More info from Chrome: https://developer.chrome.com/blog/autoplay

**Comment by carelevers** [comment]
Hi no problem,

Specifically, I am having the issue with vLite on the website I'm working on, where it's not in an iframe. This page uses version 4.2.0 of vLite, but the same problem occurs with version 6.0.3. I'm not sure if the issue is specific to vLite, as I've experienced similar problems with other packages that implement a YouTube video player. I'll try to reproduce the issue in a sandbox environment without an iframe like jsfiddle, to see if it persists. 

Here’s the link to the live site where the issue can be observed: [Live Site](https://shorturl.at/rY756).

Thank you for your assistance.

**Comment by carelevers** [comment]
Hi, I managed to fix it! It wasn’t something with Vlitejs after all, sorry for the confusion :)

The issue was actually with this header in my .htaccess :
`Header always set Permissions-Policy "accelerometer=self, autoplay=self, camera=(), gyroscope=self, magnetometer=(), microphone=(), payment=(), publickey-credentials-get=(), usb=()"`

Specifically, the autoplay=self policy 

Thanks for the help anyway!
