### ISSUE TITLE
No total time is shown if preload='none' is used

### ISSUE THREAD

**Issue by ignl** [vlitejs/vlite#135]
### Describe the bug

If I change to preload='metadata' then total time is OK otherwise it's 00:00.

### Steps to reproduce

Create video player with preload='none'

### Expected behavior

Total time is visible regardless of preload option.

### Vlite.js

6.0.2

### Browser

All

### OS

All

**Comment by yoriiis** [comment]
Hello @ignl, thanks for the report!
Can you look at the changes and test on your side too (https://github.com/vlitejs/vlite/pull/136)?
