### ISSUE TITLE
Problem with pause on 2nd video playback if poster is installed

### ISSUE THREAD

**Issue by fedorovz** [vlitejs/vlite#142]
### Describe the bug

If the video has a poster option, then when a new playback starts after a pause, the poster will be displayed in the background instead of the video frame.

### Steps to reproduce

1. Set video poster option in options
![Screenshot from 2024-10-15 15-51-54](https://github.com/user-attachments/assets/42c1d8f1-dec0-44c1-892b-bbf7689add26)

2. Start to play video
3. Wait until the video ends.
4. Play the video again
5. Pause the video.

### Expected behavior

After playing the video a second time, when paused, the background should not be a poster.

### Screenshots and recordings

Pause at first play:
![Screenshot from 2024-10-15 16-01-55](https://github.com/user-attachments/assets/074fde5c-e35b-4aea-98fb-77e2c328b37b)

Pause at second play:
![Screenshot from 2024-10-15 16-02-05](https://github.com/user-attachments/assets/86de2d03-a2ec-4127-8a44-f760a5aa78da)

Video of issue:
[issue.webm](https://github.com/user-attachments/assets/03822ed1-da12-410e-b588-28ac7b04f008)

### Vlite.js

6.0.4

### Browser

Chromium 129.0.6668.100 (Official Build) snap (64-bit)

### OS

Ubuntu 22.04.5 LTS

### Additional context

As I understand it, the whole problem is that after the first playback the class "v-active" is set and because of this the poster is shown if you pause during subsequent playbacks.
![image](https://github.com/user-attachments/assets/aed104f6-33a6-45f9-82e9-9ce907fd405c)

**Comment by yoriiis** [comment]
Hello @fedorovz, could you please share a small reproducible repository? Thanks

**Comment by fedorovz** [comment]
Hi @yoriiis, I hope "codepen" will be enough to check and understand the problem.
https://codepen.io/fedorovz/pen/NWQvLyP

**Comment by yoriiis** [comment]
Hi @fedorovz, thanks for the CodePen and well done for this bug.

It was missing a reset of the pause state at the end of media playback. The fix is available in this #144 if you want to check.

---

FYI, the CodePen demo has a JavaScript error because you didn't import the script for the `volume-bar` plugin. This may create errors on your side.

![image](https://github.com/user-attachments/assets/29445737-1984-4d30-bae3-695de5dde514)

**Comment by yoriiis** [comment]
This has been fixed and merged in `main`.
Release [`6.0.5`](https://github.com/yoriiis/vlitejs/releases/tag/6.0.5) is available ! 🎉
