### ISSUE TITLE
Loading  subtitles from server and display over YouTube video

### ISSUE THREAD

**Issue by shaktis110** [vlitejs/vlite#66]
### Describe the bug

Hello sir 
I am using vlitejs player on my ionic app to play YouTube videos.
YouTube video plays great.
I just want to know one thing 
Is it possible to load subtitles from server and display over YouTube video ?

### Steps to reproduce

Ionic Cordova run android

### Expected behavior

Subtitles must be loaded from the server

### Vlite.js

4.0.5

### Browser

Chrome 92

### OS

Macos 11.5.2

**Comment by yoriiis** [comment]
Hello @shaktis110, the plugin [PIP](https://github.com/vlitejs/vlite/blob/main/src/plugins/pip/README.md) and [Subtitle](https://github.com/vlitejs/vlite/blob/main/src/plugins/subtitle/README.md) are only available with the HTML5 video player.
