### ISSUE TITLE
Vlite player not showing when used in `onMounted` lifecycle hook in Vue

### ISSUE THREAD

**Issue by ThatOneCalculator** [vlitejs/vlite#68]
### Describe the bug

Trying to use a basic player with PIP plugin shows `TypeError: this.media is null` in console

### Steps to reproduce

```
new Vlitejs('#player', {
	plugins: ['pip'],
});
```

Full file: https://github.com/ThatOneCalculator/misskey/blob/55e389ba615c429349dd6e0a5dedb97028daca5b/packages/client/src/components/media-video.vue

### Expected behavior

video plays

### Screenshots and recordings

TypeError: this.media is null

![image](https://user-images.githubusercontent.com/44733677/178901432-ace63404-8bfc-4554-84db-8eb0d49b9adb.png)

### Vlite.js

4.0.6

### Browser

Firefox

### OS

Linux

### Additional context

https://stop.voring.me/notes/92ky9opshb

**Comment by syuilo** [comment]
use onMounted lifecycle hook

**Comment by ThatOneCalculator** [comment]
I did
```
import Vlitejs from 'vlitejs';
import VlitejsPip from 'vlitejs/dist/plugins/pip';
import { defaultStore } from '@/store';

const props = defineProps<{
	video: misskey.entities.DriveFile;
}>();

const videoEl = $ref<HTMLVideoElement | null>();

onMounted(() => {
	if (videoEl) {
		Vlitejs.registerPlugin('pip', VlitejsPip);
		new Vlitejs('#player', {
			plugins: ['pip'],
		});
	}
});
```

which fixes the error, but the video loads with the default player and not Vlitejs. Probably my fault still...
