### ISSUE TITLE
v-progressBar missing height CSS declaration

### ISSUE THREAD

**Issue by squareclouds** [vlitejs/vlite#70]
### Describe the bug

the v-progressBar has not height declaration, but the CSS variable --vlite-progressBarHeight exists.

### Steps to reproduce

change --vlite-progressBarHeight and checkresults in browser dev tools. the progress bar does not change heights, since
the variable is not being used anywhere by default.

### Expected behavior

change of the bar adjusts depending on the value of the variable

### Vlite.js

4.0.6

### Browser

all

### OS

macos

**Comment by yoriiis** [comment]
Hi @squareclouds, thanks for the report.

This has been fixed and merged in `main`.
Release [`4.0.7`](https://github.com/yoriiis/vlitejs/releases/tag/4.0.7) is available ! 🎉
