### ISSUE TITLE
VolumeBar control

### ISSUE THREAD

**Issue by maxdev-jh** [vlitejs/vlite#89]
### If the feature request is for a plugin or provider, specify it here.

Player options or basic feature

### If the feature solves a problem you have, specify it here.

Can't increase or decrease volume in player control bar. (Just mute or not)

Ordinary users would not think of adjusting volume with a keyboard shortcuts, maybe.

### Describe the proposed feature.

It's a very good and lightweight player but I can't found volume up/down control(VolumeBar).

It would be nice to be able to easily adjust volume from the control bar basically.

Thanks.

**Comment by yoriiis** [comment]
Hello @maxdev-jh, thanks for the feature request!
It could be a plugin to keep the core light. Would you be interested in developing it?

**Comment by fx1234** [comment]
That would be such an important feature. We would like to use the player, but without the volume slider in 2023, it doesn't make sense... too bad

**Comment by yoriiis** [comment]
FYI, the volume bar plugin is available in the release [`5.0.0`](https://github.com/yoriiis/vlitejs/releases/tag/5.0.0)
